name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            host: linux
            qtArch: gcc_64
            arch: x64
          - os: ubuntu-22.04-arm64
            host: linux
            qtArch: aarch64
            arch: arm64
          - os: windows-latest
            host: windows
            qtArch: win64_msvc2019_64
            arch: x64
          - os: windows-latest
            host: windows
            qtArch: win64_msvc2019_arm64
            arch: arm64
          - os: macos-latest
            host: macos
            qtArch: clang_64
            arch: x64
    env:
      QT_OUT_DIR: ${{ github.workspace }}/Qt
      QT_INSTALL_DIR: ${{ env.QT_OUT_DIR }}/6.6.3/${{ matrix.qtArch }}
      CMAKE_PREFIX_PATH: ${{ env.QT_INSTALL_DIR }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install aqtinstall
        run: pip install --upgrade pip aqtinstall

      - name: Install Qt ${{ matrix.qtArch }}
        run: |
          python -m aqt install-qt ${{ matrix.host }} desktop 6.6.3 ${{ matrix.qtArch }} --outputdir Qt

      - name: Configure with CMake
        run: |
          mkdir -p build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          cd build
          cpack -G ZIP

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YAP-${{ matrix.os }}-${{ matrix.arch }}
          path: build/*.zip
