name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            host: linux
            qtArch: gcc_64
            arch: x64
          - os: ubuntu-22.04-arm64
            host: linux
            qtArch: aarch64
            arch: arm64
          - os: windows-latest
            host: windows
            qtArch: win64_msvc2019_64
            arch: x64
          - os: windows-latest
            host: windows
            qtArch: win64_msvc2019_arm64
            arch: arm64
          - os: macos-latest
            host: mac
            qtArch: clang_64
            arch: x64

    steps:
      - name: Setup Python & aqtinstall
        run: |
          python3 -m pip install --upgrade pip
          pip install aqtinstall
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          python3 -m aqt install-qt ${{ matrix.host }} desktop 6.6.3 ${{ matrix.qtArch }} --outputdir Qt

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=$PWD/Qt/${{ matrix.host }}/6.6.3/${{ matrix.qtArch }}

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YAP-${{ matrix.host }}-${{ matrix.arch }}
          path: build
