name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            host: linux
            qtArch: gcc_64
          - os: ubuntu-22.04-arm64
            host: linux
            qtArch: aarch64
          - os: windows-latest
            host: windows
            qtArch: win64_msvc2019_64
          - os: macos-latest
            host: mac
            qtArch: clang_64
          - os: macos-latest
            host: mac
            qtArch: clang_arm64
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.27'

      - name: Install Qt installer
        run: pip install aqtinstall

      - name: Install Qt
        run: |
          python3 -m aqt install-qt ${{ matrix.host }} desktop 6.6.3 ${{ matrix.qtArch }} --outputdir Qt --confirm-architectures

      - name: Configure with CMake
        run: |
          cmake -B build -S . -DCMAKE_PREFIX_PATH=$PWD/Qt/6.6.3/${{ matrix.qtArch }} \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: yap-${{ matrix.host }}-${{ matrix.qtArch }}
          path: build/Release
          retention-days: 7
