name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            host: linux
            arch: x64
          - os: ubuntu-22.04-arm64
            host: linux
            arch: arm64
          - os: windows-latest
            host: windows
            arch: x64
          - os: windows-latest
            host: windows
            arch: arm64
          - os: macos-latest
            host: mac
            arch: x64
          - os: macos-latest
            host: mac
            arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.3
          host: ${{ matrix.host }}
          arch: ${{ matrix.arch }}

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload build artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.host }}-${{ matrix.arch }}
          path: build
